basic_scaling:
  idle_timeout: 10m
  max_instances: 1
entrypoint: gunicorn -b :$PORT app:app
env_variables:
  AUDIO_FMT: wav
  VIDEO_FMT: mov
instance_class: B1
runtime: python37
service: story-creator
